services:
  web:
    build:
      context: web
    container_name: team_060_web
    ports:
      - 3000:3000
    depends_on:
      - server
    volumes:
      - ./web:/app
      - /app/node_modules

  server:
    build:
      context: server
    container_name: team_060_server
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: team_06_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecret
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
